// Platform playbook: distribution-surface specs that drive generation prompts,
// UI rendering, and the visibility rubric. Limits reflect current platform
// rules; "algo" captures what each surface actually rewards.

export const PLATFORMS = {
  youtube_long: {
    id: 'youtube_long',
    label: 'YouTube — Long form',
    group: 'video',
    icon: 'YT',
    aiWeight: 10,
    algo: 'Watch time + CTR + session starts. Transcripts are indexed by Google AND cited by ChatGPT/Perplexity/Gemini — long-form YouTube is the single highest-leverage AI-visibility surface. Chapters become jump-to answers in search. YouTube is positioning as television: produce premium EPISODIC content (connected-TV worthy), and know that the first 60 seconds are scanned to classify the video — answer the title question there, then escalate to a bigger one.',
    limits: { title: 100, description: 5000, tags: 500 },
    cadence: 'Weekly. Consistency beats volume.',
    fields: [
      { key: 'title', label: 'Title', hint: 'Front-load keyword + curiosity, <= 60 chars visible' },
      { key: 'hook_script', label: 'Cold open (0–30s)', hint: 'Hook, then super-hook (why you are the authority), then the promise. First 10 seconds carry the SEO keywords aloud.' },
      { key: 'script', label: 'Full script', long: true, hint: 'Spoken-word script alternating [ON CAMERA] sections (the big direct-to-camera beats) with [B-ROLL: exact footage cue] sections, each marker on its own line; re-engage every ~15s; show stakes; one planned personality moment; consistent open/close ritual' },
      { key: 'chapters', label: 'Chapters', hint: '00:00 keyword-rich chapter titles, question-form where natural' },
      { key: 'description', label: 'Description', long: true, hint: 'Paste-ready structure: lines 1-2 answer-first (first 150 chars are the search snippet); blank line; chapter list mirroring the chapters field; [FILL] links block; keyword-rich paragraph; 2-3 hashtags' },
      { key: 'tags', label: 'Tags', hint: 'Comma separated, entity + topic tags' },
      { key: 'pinned_comment', label: 'Pinned comment', hint: 'Question that seeds discussion + CTA' },
      { key: 'thumbnail_concept', label: 'Thumbnail concept', hint: '<= 4-word overlay text, exact composition and colors, face + emotion direction, must read at 120px wide' },
      { key: 'end_screen_cta', label: 'End screen CTA' },
      { key: 'next_hook', label: 'Next-episode hook', hint: 'The closing line that opens a loop only the next episode closes — serialized retention is how series compound' },
      { key: 'playlist', label: 'Playlist & clustering', hint: 'Which series playlist this belongs to + how title/thumbnail/description mirror the series style so YouTube clusters and auto-serves the next episode' },
      { key: 'broll_map', label: 'B-roll map (your clips → script beats)', long: true, hint: 'Assign each attached library asset BY NAME to the script section it covers, in order; mark missing footage as [SHOOT: what to capture — always a beginning (walking in) and an ending (walking out), 10-30s holds]. This is the edit plan for CapCut.' },
      { key: 'todo', label: 'What I still need from you', long: true, hint: 'Bullet list of every [FILL], real number, link, or piece of footage the creator must supply before posting — nothing else blocks publishing' },
    ],
  },
  youtube_shorts: {
    id: 'youtube_shorts',
    label: 'YouTube Shorts',
    group: 'video',
    icon: 'YS',
    aiWeight: 7,
    algo: 'Swipe-away rate in first 2s decides reach. Loops count. Shorts feed long-form discovery; put the payoff early and restate the niche keyword aloud (auto-captions are indexed).',
    limits: { title: 100, description: 5000 },
    cadence: '3-5x per week.',
    // Auto-Produce guardrails: the classic Shorts shelf tops out at 60s,
    // and short-form pacing wants faster cuts than long-form.
    videoSpec: { slot: 3, targetSeconds: 45, maxSeconds: 58 },
    fields: [
      { key: 'hook', label: 'Hook (0-2s)', hint: 'Visual + verbal pattern interrupt' },
      { key: 'script', label: 'Script (<= 45s spoken)', long: true },
      { key: 'title', label: 'Title', hint: 'Keyword-first, includes #Shorts where useful' },
      { key: 'description', label: 'Description' },
      { key: 'overlay_text', label: 'On-screen text beats', hint: 'Line per beat' },
      { key: 'loop_note', label: 'Loop design', hint: 'How the end feeds the start' },
      { key: 'production_notes', label: 'Production plan (CapCut)', long: true, hint: 'Step-by-step in CapCut: template/audio search terms, auto-captions on, cover text, 9:16 export settings, then upload natively in the YouTube app' },
    ],
  },
  instagram_reel: {
    id: 'instagram_reel',
    label: 'Instagram Reel',
    group: 'video',
    icon: 'IGr',
    aiWeight: 6,
    algo: 'Sends (shares via DM) are the #1 ranking signal, then watch time. Meta AI reads captions, on-screen text and audio. SEO: keywords in caption + alt text + audio spoken words. 3-5 hashtags, not 30.',
    limits: { caption: 2200, hashtags: 5 },
    cadence: '3-4x per week.',
    // Reels beyond 90s lose recommendation eligibility on Meta surfaces;
    // the sweet spot is far shorter.
    videoSpec: { slot: 3, targetSeconds: 45, maxSeconds: 85 },
    fields: [
      { key: 'hook', label: 'Hook (0-2s)' },
      { key: 'script', label: 'Script / beat sheet', long: true },
      { key: 'caption', label: 'Caption', long: true, hint: 'First 125 chars carry the idea; line breaks; CTA = save/send' },
      { key: 'overlay_text', label: 'On-screen text beats' },
      { key: 'hashtags', label: 'Hashtags (3-5)' },
      { key: 'alt_text', label: 'Alt text', hint: 'Describe scene + entity + location, <= 125 chars' },
      { key: 'audio_note', label: 'Audio strategy', hint: 'Trending vs original; original audio names the niche' },
      { key: 'share_trigger', label: 'Send trigger', hint: 'Why someone DMs this to a friend' },
      { key: 'production_notes', label: 'Production plan (Edits app)', long: true, hint: 'Step-by-step in Meta\'s Edits app: what to search for a trending audio that fits, caption burn-in, cover text, 9:16 export — then post natively from the app for full reach' },
    ],
  },
  instagram_carousel: {
    id: 'instagram_carousel',
    label: 'Instagram Carousel',
    group: 'social',
    icon: 'IGc',
    aiWeight: 6,
    algo: 'Highest save rate of any IG format. Slide 1 = headline promise; each slide one idea; last slide CTA. Carousels get a second impression serve when swiped. Saves + sends drive reach.',
    limits: { caption: 2200, slides: 10, hashtags: 5 },
    cadence: '1-2x per week.',
    fields: [
      { key: 'slides', label: 'Slides (cover → CTA)', long: true, hint: 'Numbered; slide text + visual direction per slide' },
      { key: 'caption', label: 'Caption', long: true },
      { key: 'hashtags', label: 'Hashtags (3-5)' },
      { key: 'alt_text', label: 'Alt text per slide', long: true },
      { key: 'save_trigger', label: 'Save trigger', hint: 'Reference value: checklist, framework, prices' },
    ],
  },
  tiktok: {
    id: 'tiktok',
    label: 'TikTok',
    group: 'video',
    icon: 'TT',
    aiWeight: 6,
    algo: 'TikTok is a search engine for under-35s and is crawled for AI answers. Keyword in: spoken audio (first 5s), on-screen text, caption. Watch-through + rewatch + search-bar taps rank it. Comments compound reach.',
    limits: { caption: 2200, hashtags: 6 },
    cadence: '1x daily if possible.',
    // TikTok's own guidance favors clips in the 20s to 35s band; full
    // watch-throughs rank, so shorter wins.
    videoSpec: { slot: 3, targetSeconds: 34, maxSeconds: 58 },
    fields: [
      { key: 'hook', label: 'Hook (0-2s)' },
      { key: 'script', label: 'Script', long: true },
      { key: 'caption', label: 'Caption', hint: 'Keyword phrase early; question to seed comments' },
      { key: 'overlay_text', label: 'On-screen text beats' },
      { key: 'hashtags', label: 'Hashtags (3-6)', hint: 'Niche > broad; no #fyp spam' },
      { key: 'search_phrase', label: 'Target search phrase', hint: 'What someone types into TikTok search' },
      { key: 'comment_seed', label: 'Comment seed', hint: 'First comment you post to steer discussion' },
      { key: 'production_notes', label: 'Production plan (CapCut)', long: true, hint: 'Step-by-step in CapCut: trending audio/template search terms for TODAY, auto-captions, text timing, cover frame, then post natively from TikTok to keep audio rights + reach' },
    ],
  },
  facebook: {
    id: 'facebook',
    label: 'Facebook',
    group: 'social',
    icon: 'FB',
    aiWeight: 5,
    algo: 'Meaningful-interaction ranking: comments + shares from real conversation. Engagement RATIO beats follower count — a smaller, active group outranks a large dead page. Native video + photo dumps outperform links. Storytelling posts (150-400 words) with a question outperform broadcast copy. 0-2 hashtags.',
    limits: { post: 63206, hashtags: 2 },
    cadence: '4-5x per week.',
    fields: [
      { key: 'post', label: 'Post', long: true, hint: 'Story-first; hook line; white space; question close' },
      { key: 'reel_caption', label: 'Reel caption (if video)', hint: 'Short, send-worthy' },
      { key: 'group_variant', label: 'Group-friendly variant', long: true, hint: 'Value-only rewrite for communities, no self-promo' },
      { key: 'cta', label: 'CTA' },
    ],
  },
  x_thread: {
    id: 'x_thread',
    label: 'X / Twitter thread',
    group: 'social',
    icon: 'X',
    aiWeight: 6,
    algo: 'Threads are scraped heavily by LLMs and quoted in AI answers. Tweet 1 = the entire promise (it is the ad). One idea per tweet, concrete numbers, no hashtags in body. Reply-to-own-thread within 1h boosts.',
    limits: { tweet: 280 },
    cadence: '2-3 threads per week.',
    fields: [
      { key: 'tweets', label: 'Thread (numbered tweets)', long: true, hint: '7-12 tweets; each <= 280 chars; hooks at 1, re-hook at 4' },
      { key: 'hook_variants', label: 'Alt hooks for tweet 1 (x3)', long: true },
      { key: 'quote_bait', label: 'Quotable line', hint: 'The one-liner people screenshot' },
    ],
  },
  linkedin: {
    id: 'linkedin',
    label: 'LinkedIn',
    group: 'social',
    icon: 'LI',
    aiWeight: 8,
    algo: 'Dwell time + early comments (first 90 min). LinkedIn articles + posts are indexed by Google and cited by AI engines for professional queries — strong E-E-A-T surface. First 210 chars decide the "see more" click. 3-5 hashtags.',
    limits: { post: 3000, headline: 210, hashtags: 5 },
    cadence: '3-4 posts + 1 article per week.',
    fields: [
      { key: 'post', label: 'Post', long: true, hint: 'Line 1 hook <= 210 chars; short lines; personal proof; question close' },
      { key: 'article_title', label: 'Article title', hint: 'Question-form or claim-form, keyword-first' },
      { key: 'article', label: 'Article body', long: true, hint: 'Markdown with explicit hierarchy: # H1 once, ## question-form H2 per section, ### sub-points; a "**Key takeaways**" 3-bullet block right after the intro; the first paragraph under each ## is a 40-60 word standalone answer; stats; experience blocks; MUST end with a "## FAQ" section of 3 spoken-query Q&As. This same article ships to your website via the Website Kit.' },
      { key: 'hashtags', label: 'Hashtags (3-5)' },
      { key: 'comment_starter', label: 'First comment', hint: 'Add a resource or bonus point in your own first comment' },
    ],
  },
  gbp: {
    id: 'gbp',
    label: 'Google Business Profile',
    group: 'local',
    icon: 'G',
    aiWeight: 9,
    algo: 'GBP posts, Q&A, services and photos feed Google AI Overviews and Gemini for ANY local/service query. Keyword-rich updates + photo uploads with geo-context + fresh Q&A pairs = direct AI-answer inclusion.',
    limits: { post: 1500 },
    cadence: 'Weekly updates + monthly Q&A refresh.',
    fields: [
      { key: 'post', label: 'Update post', long: true, hint: '<= 1500 chars, keyword + city + service, one CTA button choice' },
      { key: 'cta_button', label: 'CTA button', hint: 'Learn more / Book / Call' },
      { key: 'qa_pairs', label: 'Q&A pairs (ask + answer yourself)', long: true, hint: '3 question/answer pairs, conversational query phrasing' },
      { key: 'photo_captions', label: 'Photo upload notes', long: true, hint: 'Which media to upload + geo-tagged descriptions' },
    ],
  },
  alignable: {
    id: 'alignable',
    label: 'Alignable',
    group: 'local',
    icon: 'AL',
    aiWeight: 3,
    algo: 'Small-business referral network: local peers, not consumers. Wins come from generosity — introductions, local Q&A answers, event posts. Write to fellow owners, never at customers.',
    limits: { post: 3000 },
    cadence: '1-2x per week.',
    fields: [
      { key: 'post', label: 'Post', long: true, hint: 'Peer-to-peer voice; local angle; offer help or a referral' },
      { key: 'question', label: 'Community question', hint: 'A question that positions your expertise' },
    ],
  },
  pinterest: {
    id: 'pinterest',
    label: 'Pinterest',
    group: 'discovery',
    icon: 'P',
    aiWeight: 6,
    algo: 'A visual search engine with 6-12 MONTH content life. Keywords live in pin title, description, and board name — not hashtags. Idea Pins + fresh vertical images (2:3) rank; text overlay is OCR-read.',
    limits: { title: 100, description: 500 },
    cadence: '3-5 pins per week.',
    fields: [
      { key: 'pin_title', label: 'Pin title', hint: 'Keyword-first, <= 100 chars' },
      { key: 'pin_description', label: 'Pin description', long: true, hint: '<= 500 chars, natural keyword sentences, CTA' },
      { key: 'board', label: 'Board name + description', hint: 'Keyword-rich board placement' },
      { key: 'overlay_text', label: 'Image text overlay', hint: 'Readable at thumbnail size' },
      { key: 'idea_pin_pages', label: 'Idea Pin pages', long: true, hint: 'Page-by-page text if multi-page' },
    ],
  },
  newsletter: {
    id: 'newsletter',
    label: 'Newsletter (Beehiiv)',
    group: 'owned',
    icon: 'NL',
    aiWeight: 7,
    algo: 'The only audience you own — no algorithm between you and the reader. Beehiiv web versions are crawlable pages: enable them (custom domain if you can) so every issue is also an indexed article. Deliverability: one idea, one CTA, subject under 50 chars, no spam-trigger words. Tue-Thu mornings send best.',
    limits: { subject: 70, preview_text: 140 },
    cadence: 'Weekly minimum — same day every week.',
    fields: [
      { key: 'subject', label: 'Subject line', hint: '<= 50 chars, specific + curious, no spam words (free!!!, act now)' },
      { key: 'subject_b', label: 'A/B subject variant', hint: 'Different psychological angle (curiosity vs proof vs urgency)' },
      { key: 'preview_text', label: 'Preview text', hint: '40-90 chars that COMPLETE the subject, never repeat it' },
      { key: 'body', label: 'Email body', long: true, hint: 'Story-first open; short paragraphs; ## headers (they render in the web version); one CTA mid and one at end; close with the FAQ pairs so the crawlable web version carries the answer layer' },
      { key: 'cta_button', label: 'CTA button label', hint: '3-5 words' },
      { key: 'ps_line', label: 'P.S. line', hint: 'Second-most-read line of any email — human note or true urgency' },
      { key: 'web_note', label: 'Beehiiv web-version settings', hint: 'SEO title + meta description for this issue; confirm web version is on' },
    ],
  },
  reddit: {
    id: 'reddit',
    label: 'Reddit',
    group: 'discovery',
    icon: 'RD',
    aiWeight: 8,
    algo: 'LLMs cite Reddit more than almost any social surface — its content is licensed into training and retrieval. But Reddit destroys self-promotion: value-first, first-person, no links in the post body, mention your offer only when asked. One genuinely useful post in the right subreddit outranks ten ads, forever.',
    limits: { title: 300 },
    cadence: '1-2 value posts per week + answering questions in niche subs.',
    fields: [
      { key: 'subreddits', label: 'Target subreddits', hint: '3-5 subs with a one-line reason each; check each sub\'s self-promo rules first' },
      { key: 'title', label: 'Post title', hint: 'Native Reddit phrasing — experience-form or question-form, zero marketing voice' },
      { key: 'post', label: 'Post', long: true, hint: 'Pure value or story, first person, specific numbers, NO links; end by inviting questions' },
      { key: 'comment_answers', label: 'Ready comment answers', long: true, hint: '2-3 prepared replies for likely questions — including how to mention the offer naturally IF someone asks' },
      { key: 'rules_note', label: 'Self-promo reality check', hint: 'What the target subs allow; when to disclose affiliation' },
    ],
  },
  bing: {
    id: 'bing',
    label: 'Bing Places / Copilot',
    group: 'local',
    icon: 'B',
    aiWeight: 5,
    algo: 'Bing Places + Bing-indexed pages feed Microsoft Copilot and ChatGPT browsing. Exact-match NAP consistency, longer keyword-complete descriptions, and category completeness matter more than on Google.',
    limits: { description: 5000 },
    cadence: 'Monthly refresh.',
    fields: [
      { key: 'description', label: 'Business description', long: true, hint: 'Complete-sentence keyword coverage; services enumerated' },
      { key: 'post', label: 'Update / announcement', long: true },
      { key: 'qa_pairs', label: 'FAQ pairs for site + Bing', long: true },
    ],
  },
};

export const PLATFORM_ORDER = [
  'youtube_long', 'youtube_shorts', 'instagram_reel', 'instagram_carousel',
  'tiktok', 'facebook', 'x_thread', 'linkedin', 'newsletter', 'reddit',
  'gbp', 'alignable', 'pinterest', 'bing',
];

export function platformList() {
  return PLATFORM_ORDER.map((id) => PLATFORMS[id]);
}
