// Platform playbook: distribution-surface specs that drive generation prompts,
// UI rendering, and the visibility rubric. Limits reflect current platform
// rules; "algo" captures what each surface actually rewards.

export const PLATFORMS = {
  youtube_long: {
    id: 'youtube_long',
    label: 'YouTube — Long form',
    group: 'video',
    icon: 'YT',
    aiWeight: 10,
    algo: 'Watch time + CTR + session starts. Transcripts are indexed by Google AND cited by ChatGPT/Perplexity/Gemini — long-form YouTube is the single highest-leverage AI-visibility surface. Chapters become jump-to answers in search.',
    limits: { title: 100, description: 5000, tags: 500 },
    cadence: 'Weekly. Consistency beats volume.',
    fields: [
      { key: 'title', label: 'Title', hint: 'Front-load keyword + curiosity, <= 60 chars visible' },
      { key: 'hook_script', label: 'Cold open (0–30s)', hint: 'Spoken hook: stake the claim, preview the payoff' },
      { key: 'script', label: 'Full script', long: true, hint: 'Spoken-word script with [B-ROLL] cues' },
      { key: 'chapters', label: 'Chapters', hint: '00:00 keyword-rich chapter titles, question-form where natural' },
      { key: 'description', label: 'Description', long: true, hint: 'First 150 chars = answer-first summary; links; keyword paragraph' },
      { key: 'tags', label: 'Tags', hint: 'Comma separated, entity + topic tags' },
      { key: 'pinned_comment', label: 'Pinned comment', hint: 'Question that seeds discussion + CTA' },
      { key: 'thumbnail_concept', label: 'Thumbnail concept', hint: '3-5 word overlay, face + emotion, high contrast' },
      { key: 'end_screen_cta', label: 'End screen CTA' },
    ],
  },
  youtube_shorts: {
    id: 'youtube_shorts',
    label: 'YouTube Shorts',
    group: 'video',
    icon: 'YS',
    aiWeight: 7,
    algo: 'Swipe-away rate in first 2s decides reach. Loops count. Shorts feed long-form discovery; put the payoff early and restate the niche keyword aloud (auto-captions are indexed).',
    limits: { title: 100, description: 5000 },
    cadence: '3-5x per week.',
    fields: [
      { key: 'hook', label: 'Hook (0-2s)', hint: 'Visual + verbal pattern interrupt' },
      { key: 'script', label: 'Script (<= 45s spoken)', long: true },
      { key: 'title', label: 'Title', hint: 'Keyword-first, includes #Shorts where useful' },
      { key: 'description', label: 'Description' },
      { key: 'overlay_text', label: 'On-screen text beats', hint: 'Line per beat' },
      { key: 'loop_note', label: 'Loop design', hint: 'How the end feeds the start' },
    ],
  },
  instagram_reel: {
    id: 'instagram_reel',
    label: 'Instagram Reel',
    group: 'video',
    icon: 'IGr',
    aiWeight: 6,
    algo: 'Sends (shares via DM) are the #1 ranking signal, then watch time. Meta AI reads captions, on-screen text and audio. SEO: keywords in caption + alt text + audio spoken words. 3-5 hashtags, not 30.',
    limits: { caption: 2200, hashtags: 5 },
    cadence: '3-4x per week.',
    fields: [
      { key: 'hook', label: 'Hook (0-2s)' },
      { key: 'script', label: 'Script / beat sheet', long: true },
      { key: 'caption', label: 'Caption', long: true, hint: 'First 125 chars carry the idea; line breaks; CTA = save/send' },
      { key: 'overlay_text', label: 'On-screen text beats' },
      { key: 'hashtags', label: 'Hashtags (3-5)' },
      { key: 'alt_text', label: 'Alt text', hint: 'Describe scene + entity + location, <= 125 chars' },
      { key: 'audio_note', label: 'Audio strategy', hint: 'Trending vs original; original audio names the niche' },
      { key: 'share_trigger', label: 'Send trigger', hint: 'Why someone DMs this to a friend' },
    ],
  },
  instagram_carousel: {
    id: 'instagram_carousel',
    label: 'Instagram Carousel',
    group: 'social',
    icon: 'IGc',
    aiWeight: 6,
    algo: 'Highest save rate of any IG format. Slide 1 = headline promise; each slide one idea; last slide CTA. Carousels get a second impression serve when swiped. Saves + sends drive reach.',
    limits: { caption: 2200, slides: 10, hashtags: 5 },
    cadence: '1-2x per week.',
    fields: [
      { key: 'slides', label: 'Slides (cover → CTA)', long: true, hint: 'Numbered; slide text + visual direction per slide' },
      { key: 'caption', label: 'Caption', long: true },
      { key: 'hashtags', label: 'Hashtags (3-5)' },
      { key: 'alt_text', label: 'Alt text per slide', long: true },
      { key: 'save_trigger', label: 'Save trigger', hint: 'Reference value: checklist, framework, prices' },
    ],
  },
  tiktok: {
    id: 'tiktok',
    label: 'TikTok',
    group: 'video',
    icon: 'TT',
    aiWeight: 6,
    algo: 'TikTok is a search engine for under-35s and is crawled for AI answers. Keyword in: spoken audio (first 5s), on-screen text, caption. Watch-through + rewatch + search-bar taps rank it. Comments compound reach.',
    limits: { caption: 2200, hashtags: 6 },
    cadence: '1x daily if possible.',
    fields: [
      { key: 'hook', label: 'Hook (0-2s)' },
      { key: 'script', label: 'Script', long: true },
      { key: 'caption', label: 'Caption', hint: 'Keyword phrase early; question to seed comments' },
      { key: 'overlay_text', label: 'On-screen text beats' },
      { key: 'hashtags', label: 'Hashtags (3-6)', hint: 'Niche > broad; no #fyp spam' },
      { key: 'search_phrase', label: 'Target search phrase', hint: 'What someone types into TikTok search' },
      { key: 'comment_seed', label: 'Comment seed', hint: 'First comment you post to steer discussion' },
    ],
  },
  facebook: {
    id: 'facebook',
    label: 'Facebook',
    group: 'social',
    icon: 'FB',
    aiWeight: 5,
    algo: 'Meaningful-interaction ranking: comments + shares from real conversation. Native video + photo dumps outperform links. Storytelling posts (150-400 words) with a question outperform broadcast copy. 0-2 hashtags.',
    limits: { post: 63206, hashtags: 2 },
    cadence: '4-5x per week.',
    fields: [
      { key: 'post', label: 'Post', long: true, hint: 'Story-first; hook line; white space; question close' },
      { key: 'reel_caption', label: 'Reel caption (if video)', hint: 'Short, send-worthy' },
      { key: 'group_variant', label: 'Group-friendly variant', long: true, hint: 'Value-only rewrite for communities, no self-promo' },
      { key: 'cta', label: 'CTA' },
    ],
  },
  x_thread: {
    id: 'x_thread',
    label: 'X / Twitter thread',
    group: 'social',
    icon: 'X',
    aiWeight: 6,
    algo: 'Threads are scraped heavily by LLMs and quoted in AI answers. Tweet 1 = the entire promise (it is the ad). One idea per tweet, concrete numbers, no hashtags in body. Reply-to-own-thread within 1h boosts.',
    limits: { tweet: 280 },
    cadence: '2-3 threads per week.',
    fields: [
      { key: 'tweets', label: 'Thread (numbered tweets)', long: true, hint: '7-12 tweets; each <= 280 chars; hooks at 1, re-hook at 4' },
      { key: 'hook_variants', label: 'Alt hooks for tweet 1 (x3)', long: true },
      { key: 'quote_bait', label: 'Quotable line', hint: 'The one-liner people screenshot' },
    ],
  },
  linkedin: {
    id: 'linkedin',
    label: 'LinkedIn',
    group: 'social',
    icon: 'LI',
    aiWeight: 8,
    algo: 'Dwell time + early comments (first 90 min). LinkedIn articles + posts are indexed by Google and cited by AI engines for professional queries — strong E-E-A-T surface. First 210 chars decide the "see more" click. 3-5 hashtags.',
    limits: { post: 3000, headline: 210, hashtags: 5 },
    cadence: '3-4 posts + 1 article per week.',
    fields: [
      { key: 'post', label: 'Post', long: true, hint: 'Line 1 hook <= 210 chars; short lines; personal proof; question close' },
      { key: 'article_title', label: 'Article title', hint: 'Question-form or claim-form, keyword-first' },
      { key: 'article', label: 'Article body', long: true, hint: 'H2s as questions; answer-first paragraphs; stats; experience blocks' },
      { key: 'hashtags', label: 'Hashtags (3-5)' },
      { key: 'comment_starter', label: 'First comment', hint: 'Add a resource or bonus point in your own first comment' },
    ],
  },
  gbp: {
    id: 'gbp',
    label: 'Google Business Profile',
    group: 'local',
    icon: 'G',
    aiWeight: 9,
    algo: 'GBP posts, Q&A, services and photos feed Google AI Overviews and Gemini for ANY local/service query. Keyword-rich updates + photo uploads with geo-context + fresh Q&A pairs = direct AI-answer inclusion.',
    limits: { post: 1500 },
    cadence: 'Weekly updates + monthly Q&A refresh.',
    fields: [
      { key: 'post', label: 'Update post', long: true, hint: '<= 1500 chars, keyword + city + service, one CTA button choice' },
      { key: 'cta_button', label: 'CTA button', hint: 'Learn more / Book / Call' },
      { key: 'qa_pairs', label: 'Q&A pairs (ask + answer yourself)', long: true, hint: '3 question/answer pairs, conversational query phrasing' },
      { key: 'photo_captions', label: 'Photo upload notes', long: true, hint: 'Which media to upload + geo-tagged descriptions' },
    ],
  },
  alignable: {
    id: 'alignable',
    label: 'Alignable',
    group: 'local',
    icon: 'AL',
    aiWeight: 3,
    algo: 'Small-business referral network: local peers, not consumers. Wins come from generosity — introductions, local Q&A answers, event posts. Write to fellow owners, never at customers.',
    limits: { post: 3000 },
    cadence: '1-2x per week.',
    fields: [
      { key: 'post', label: 'Post', long: true, hint: 'Peer-to-peer voice; local angle; offer help or a referral' },
      { key: 'question', label: 'Community question', hint: 'A question that positions your expertise' },
    ],
  },
  pinterest: {
    id: 'pinterest',
    label: 'Pinterest',
    group: 'discovery',
    icon: 'P',
    aiWeight: 6,
    algo: 'A visual search engine with 6-12 MONTH content life. Keywords live in pin title, description, and board name — not hashtags. Idea Pins + fresh vertical images (2:3) rank; text overlay is OCR-read.',
    limits: { title: 100, description: 500 },
    cadence: '3-5 pins per week.',
    fields: [
      { key: 'pin_title', label: 'Pin title', hint: 'Keyword-first, <= 100 chars' },
      { key: 'pin_description', label: 'Pin description', long: true, hint: '<= 500 chars, natural keyword sentences, CTA' },
      { key: 'board', label: 'Board name + description', hint: 'Keyword-rich board placement' },
      { key: 'overlay_text', label: 'Image text overlay', hint: 'Readable at thumbnail size' },
      { key: 'idea_pin_pages', label: 'Idea Pin pages', long: true, hint: 'Page-by-page text if multi-page' },
    ],
  },
  bing: {
    id: 'bing',
    label: 'Bing Places / Copilot',
    group: 'local',
    icon: 'B',
    aiWeight: 5,
    algo: 'Bing Places + Bing-indexed pages feed Microsoft Copilot and ChatGPT browsing. Exact-match NAP consistency, longer keyword-complete descriptions, and category completeness matter more than on Google.',
    limits: { description: 5000 },
    cadence: 'Monthly refresh.',
    fields: [
      { key: 'description', label: 'Business description', long: true, hint: 'Complete-sentence keyword coverage; services enumerated' },
      { key: 'post', label: 'Update / announcement', long: true },
      { key: 'qa_pairs', label: 'FAQ pairs for site + Bing', long: true },
    ],
  },
};

export const PLATFORM_ORDER = [
  'youtube_long', 'youtube_shorts', 'instagram_reel', 'instagram_carousel',
  'tiktok', 'facebook', 'x_thread', 'linkedin', 'gbp', 'alignable',
  'pinterest', 'bing',
];

export function platformList() {
  return PLATFORM_ORDER.map((id) => PLATFORMS[id]);
}
